### ISSUE TITLE
AttributeError: 'Config' object has no attribute '_metadata'

### ISSUE THREAD

**Issue by bitnik** [ansible-community/pytest-molecule#117]
Today we get the following error when we run pytest for molecule tests:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 995, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pytest_molecule/__init__.py", line 70, in pytest_configure
INTERNALERROR>     config._metadata["Packages"][package] = pkg_resources.get_distribution(
INTERNALERROR> AttributeError: 'Config' object has no attribute '_metadata'
```

We found out that the error is related to `pytest-metadata` package which had a [new major release yesterday](https://github.com/pytest-dev/pytest-metadata/tags). If we downgrade it to version 1.11.0, then we don't get any error.

This `pytest-metadata` package is required by `pytest-html`, which is required by `pytest-molecule`, and it [install pytest-metadata whithout any limit on the version](https://github.com/pytest-dev/pytest-html/blob/master/setup.py#L16).

**Comment by bitnik** [comment]
Btw looking at the [changes in pytest-metadata](https://github.com/pytest-dev/pytest-metadata/compare/v1.11.0...v2.0.0), I can't find out what could cause the problem. `config._metadata` is used there as well.

**Comment by ssbarnea** [comment]
I am core on pytest-html but not on pytest-metadata. Still I might be able to pull some strings if a working PR is available to update any of them.

**Comment by LeiYangGH** [comment]
i met same issue for `pytest-metadata` 2.x, also solved by downgrade to 1.x.
